version: "3.9"
services:
  db:
    container_name: postgres_db
    image: postgres:14.4-alpine
    restart: always
    ports:
      - "${TYPEORM_PORT:-5432}:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-disciplinas}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-a1s2d3}
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=sodd
      - POSTGRES_PASSWORD=a1s2d3
      - PORT=3333
      - NODE_ENV=development
      - TYPEORM_HOST=host.docker.internal
      - TYPEORM_PORT=5432
      - TYPEORM_USERNAME=postgres
      - TYPEORM_PASSWORD=a1s2d3
      - TYPEORM_DATABASE=sodd
      - TYPEORM_SYNCHRONIZE=false
      - DATABASE_URL=postgres://postgres:a1s2d3@host.docker.internal:5432/sodd
    volumes:
      - /app/node_modules
      - ./src:/app/src
    ports:
      - "${PORT:-3333}:3333"
